[supabase]
url = "https://xixtvdzauqlgvyrigfam.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhpa3R2ZHphdXFsZ3Z5cmlnZmFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDAzNjcsImV4cCI6MjA2NTIxNjM2N30.poPK_WfD2Kz9SXuYTdYxyOs9Exwq0BAZ1hJnSr9NSvw"
